### PR TITLE
update flask-app prose

### LINKED ISSUE #238: `flask-application.md` should add more details about the required yaml files [meteor]
The [deploy your application](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/model-deployment/flask-application.md#2-deploy-your-application) section provides no context or additional information about the 3 yaml files required to deploy the inference app. Since these are fairly critical to the successful deployment of the application, we should provide a short description of each and what they do and why they are needed. 

Acceptance Criteria:

- [ ]  add additional details about the deploymentconfig, route and service yaml files.

### LINKED ISSUE #239: `flask-application.md` should provide more details on the flask app wsgi.py [meteor]
The [create your Flask app section](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/model-deployment/flask-application.md#create-your-flask-app) could be improved by providing some more explanation of the flask  app. Since this is also a critical aspect of getting the service deployed correctly, it might be worth outlining the minimum required methods (like `/predict`) that need to be implemented.

### LINKED ISSUE #240: Typo in `flask-application.md` [meteor]
Step 7 in [Using OpenShift CLI](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/model-deployment/flask-application.md#using-openshift-cli) says:

`oc apply -f ./manifests/deploymentconfig.yaml`

Should be changed to:

`oc apply -f ./manifests/base/deploymentconfig.yaml`

### LINKED ISSUE #248: Add additional explanation to "Make a new release" section of `flask-application.md` [Meteor]
In the [first section](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/model-deployment/flask-application.md#1-make-a-new-release) of `flask-application.md`, "Make a new release"  there is no explanation as to why a second release needs to be made during the tutorial, as one was already done in an earlier step. More information should be added to this section:

Response from @pacospace about why we need another release:
"Yes it needs to be pushed back to the repo and a new release created to have a new model in the image. Once new tag is created, the pipeline also updates automatically the tag in the repo where ArgoCD is looking for changes:  and the image/model is already redeployed."

Acceptance Criteria:

- [ ] Add additional explanation to [Make a new release](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/docs/source/model-deployment/flask-application.md#1-make-a-new-release)

### PR DESCRIPTION
**Pull request by isabelizimm**
## Related Issues and Dependencies

closes #248 prose for new release
closes #240 typo
closes #239 details of flask app
closes #238 add yaml details

## This introduces a breaking change

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
/lgtm

**Comment by isabelizimm** [comment]
Added brief explanation of the yaml files. I tried to keep the manifest descriptions digestible for new users, LMK if I've abstracted too far from what they do in a technical sense. :)

**Review by oindrillac — COMMENTED** [review]
/lgtm

**Comment by MichaelClifford** [comment]
The description of the manifest should go in the Requirements section where they are introduced not in the CLI section.

**Comment by isabelizimm** [comment]
> The description of the manifest should go in the Requirements section where they are introduced not in the CLI section.

updated

**Review by MichaelClifford — CHANGES_REQUESTED** [review]

**Pull request merged**
