### PR TITLE
fix links in pre-requisite.md

### LINKED ISSUE #212: Link to open an issue on the opf support page does not redirect to the correct issue template
Link to open an issue on the opf support page does not redirect to the correct issue template.

replace: https://github.com/operate-first/support/issues/new?assignees=&labels=onboarding&template=onboarding_to_cluster.md&title=

with: https://github.com/operate-first/support/issues/new?assignees=first-operator&labels=kind%2Fonboarding%2Carea%2Fcluster&template=onboarding_to_cluster.yaml&title=NEW+PROJECT%3A+%3Cname%3E

on line 29 of `docs/source/pre-requisite.md`

### PR DESCRIPTION
**Pull request by MichaelClifford**
## Related Issues and Dependencies

closes  #212 and #213

## This introduces a breaking change

- [ ] Yes
- [x ] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm

**Review by isabelizimm — COMMENTED** [review]
/lgtm

**Review by isabelizimm — APPROVED** [review]

**Review by chauhankaranraj — APPROVED** [review]
/lgtm

**Pull request merged**
