### PR TITLE
remove rendered jupyterbook files

### LINKED ISSUE #268: Remove rendered jupyterbook files
With Meteor in place, we no longer need to keep the rendered Jupyterbook files in this repo. I recommend that we remove them from `/docs`.

### PR DESCRIPTION
**Pull request by MichaelClifford**
## Related Issues and Dependencies
 closes #268 by removing the rendered jupyterbook files as those are managed by project meteor now.

### CODE REVIEW

**Review by oindrillac — APPROVED** [review]
/lgtm

**Review by chauhankaranraj — APPROVED** [review]
/lgtm

**Comment by pacospace** [comment]
Thanks 💯

**Review by pacospace — APPROVED** [review]

**Pull request merged**
