### PR TITLE
modifying notebooks for automation

### PR DESCRIPTION
**Pull request by oindrillac**
## Related Issues and Dependencies
Resolves https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/185, https://github.com/AICoE/meteor/issues/37, https://github.com/AICoE/meteor/issues/24, https://github.com/AICoE/meteor/issues/23

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements
This PR modifies the `download_data` and `training` notebooks in the tutorial to make them suitable for running in automation(kfp pipeline) and for the meteor project.

## Description
* The environment variable names in both the notebooks are made consistent. - https://github.com/AICoE/meteor/issues/37
* Remove commented code and configure the segments to run based on `USE_CEPH` value - https://github.com/AICoE/meteor/issues/23
* Reduce training epochs from 10 to 1 - https://github.com/AICoE/meteor/issues/24
* Modify file path for raw dataset to run successfully in a kfp pipeline and added `data/raw` directory within `notebooks` in training notebook to resolve the errors while running in automation. - https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/185

cc: @pacospace

### CODE REVIEW

**Comment by oindrillac** [comment]
cc: @chauhankaranraj @MichaelClifford @isabelizimm

**Review by isabelizimm — APPROVED** [review]
lgtm!

**Comment by MichaelClifford** [comment]
Im not sure about duplicating the data to `notebooks/data/raw/*` folder in the repository. Could we create a temp_data directory in /notebooks while the pipeline runs, but not actually store anything in the repo?

**Comment by oindrillac** [comment]
> Im not sure about duplicating the data to `notebooks/data/raw/*` folder in the repository. Could we create a temp_data directory in /notebooks while the pipeline runs, but not actually store anything in the repo?

Elyra expects me to add file dependencies like 
image
where I need to point to the saved file due to the relative hierarchy issue.

If I only add an empty directory without the files itself and try to run the pipeline, I get a "File not found" error.
```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/pipeline/processor.py", line 275, in _upload_dependencies_to_object_store
    dependency_archive_path = self._generate_dependency_archive(operation)
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/pipeline/processor.py", line 261, in _generate_dependency_archive
    archive_artifact = create_temp_archive(archive_name=archive_artifact_name,
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/util/archive.py", line 124, in create_temp_archive
    raise FileNotFoundError(filenames_set - matched_set)  # Only include the missing filenames
FileNotFoundError: {'data/raw/xdata.pkl', 'data/raw/xtestdata.pkl', 'data/raw/ydata.pkl', 'data/raw/ytestdata.pkl'}

```
So, yes, I can rename `/data/raw` to be `temp_data`, but the relative hierarchy requirement expects me to keep the file.

**Comment by MichaelClifford** [comment]
Does this dependency requirement mean that there always needs to be an existing file in the repo that will be updated by step A to be consumed later in the pipeline by step B?

**Comment by oindrillac** [comment]
> Does this dependency requirement mean that there always needs to be an existing file in the repo that will be updated by step A to be consumed later in the pipeline by step B?

@MichaelClifford it seems to be the case, the way the notebooks are currently configured which is, step A downloads data and stores it into s3, and step 2 downloads from s3 into the local directory, replaces those dependency files and loads them in memory. 

@pacospace can you please confirm that this is the case?

**Comment by MichaelClifford** [comment]
@oindrillac yes, and that is similar to how we do it in the ai4ci project (pushing and pulling from ceph at each step). It also looks like one of the [ibm examples](https://github.com/CODAIT/covid-notebooks/tree/master/notebooks) does what you are doing here to avoid multiple ceph interactions. 

But, Looking at one of the [official demo's](https://github.com/elyra-ai/examples/tree/master/pipelines/dax_noaa_weather_data) seems like it should be possible to pass data without defining it as a pre-req.

**Comment by oindrillac** [comment]
> @oindrillac yes, and that is similar to how we do it in the ai4ci project (pushing and pulling from ceph at each step). 

I think the only difference in the workflow here is that, we are downloading the data (.pkl files) locally from Ceph and then loading into memory, due to which arises the need for accessing a local file/directory during execution.

> But, Looking at one of the [official demo's](https://github.com/elyra-ai/examples/tree/master/pipelines/dax_noaa_weather_data) seems like it should be possible to pass data without defining it as a pre-req.

I see that they configure something called the `output_files` parameter - https://github.com/elyra-ai/examples/blob/f51b6a963e09d45965478f5022033b8d0808dda6/pipelines/dax_noaa_weather_data/analyze_NOAA_weather_data.pipeline#L72 to make the output data generated from the first step available to the subsequent steps. This eliminates the need for storing to and reading from s3.

**Comment by MichaelClifford** [comment]
:+1: In that case we should be able to update the repo by adding the output files as parameters to the pipeline instead of adding them as dependencies, right? 

image

**Comment by oindrillac** [comment]
> 👍 In that case we should be able to update the repo by adding the output files as parameters to the pipeline instead of adding them as dependencies, right?

Right! we, can try that out. In that case, we eliminate writing and reading from s3 for data exchange in automation.

In that case, we can have an additional "AUTOMATION" env variable apart from the "USE_CEPH" env variable, which will help execute only the code blocks which are meant for automation. So, the notebooks can read/store in 3 manners, in automation, using s3 and locally.

**Comment by oindrillac** [comment]
I'm not sure why but even after specifying the output_file as `data/raw/xdata.pkl`
image

it gives me this error when I am trying to save the `data/raw/xdata.pkl` in download_dataset step of the workflow
image

**Comment by oindrillac** [comment]
The notebooks running in automation now use the "output_files" feature to exchange data. The `download_dataset` notebook stores the datasets in the 'data/raw' directory relative to the notebook from where the `training` notebook can access the files and train the model. 

I’m using an additional env variable “AUTOMATION” which enables this behavior.

**Comment by MichaelClifford** [comment]
Thanks for the changes @oindrillac : )

/lgtm

**Pull request merged**
