### PR TITLE
re-build JB with content changes

### LINKED ISSUE #188: Rebuild Jupyterbook files to reflect changes made in #186
#186 added relative links to some of the content pages. In order for those changes to be reflected in the [published book](https://aicoe.github.io/elyra-aidevsecops-tutorial/README.html) we need to rebuild the book and update the files in `docs/` in our repo. 

Please follow the instructions [here](https://docs.google.com/document/d/1fkLko3tG4Na_3UbGA-YzTqU-H42r-cU-skX07luyXho/edit) to include the updated html files. (if these instructions are confusing or insufficient for this task please leave a comment and we can update them).

### PR DESCRIPTION
**Pull request by oindrillac**
## Related Issues and Dependencies

Updating JB with new content changes

Resolves #188 

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by isabelizimm — COMMENTED** [review]
/lgtm

**Comment by MichaelClifford** [comment]
Do we want to updated this PR and rebuild again since its a few weeks old at this point and won't include updated from the last two sprints?

**Comment by oindrillac** [comment]
> Do we want to updated this PR and rebuild again since its a few weeks old at this point and won't include updated from the last two sprints?

@MichaelClifford yes, will update this PR with the latest content.

**Comment by oindrillac** [comment]
Whoops, deleted the PR branch by mistake which closed this PR. Maybe, its better to open a new PR with the latest content anyway.

**Pull request closed without merging**
